title: DARE 2024
description: >-
  Summer School on <br>
  Distributed and Replicated Environments (DARE 2024)
subdescription: "From 11 to 15 September | Darmstadt | Germany"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dare-summer.github.io" # the base hostname & protocol for your site, e.g. https://example.com

theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  demos:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: false
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: demos
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    # logo:
      # name: MPLR'22
      # img: ''
      # url: 'https://example.com'
    links:
      # - name: Calls
      #   menu:  
      #   - name: Call for Papers
      #     relative_url: /call/
      #   - name: Call for Posters and Demos
      #     relative_url: /posters/
      - name: About
        relative_url: /about/
      - name: Attending 
        relative_url: /attending/

      
      - name: Program
        relative_url: /program/

      # - name: Speakers
      #   relative_url: /speakers/
      - name: Important Dates
        relative_url: /important_dates/
      - name: Organization
        relative_url: /organization/

      # - name: Program
      #   relative_url: /program/
      # - name: Talks
      #   relative_url: /talks/

      
      # - name: Previous Editions
      #   menu:
      #     - name: 2022 (current)
      #       disabled: true
      #     - name: 2019
      #       relative_url: /2019/
      #     - name: 2018
      #       relative_url: /2018/

  # Main landing page
  main:
    logo:
      img: 'banner_to_change.jpg'
    links:
      # - name: Call for Papers
      #   relative_url: /call/
      # - name: Accepted Papers
      #   relative_url: /talks/
      # - name: Call for Posters and Demos
      #   relative_url: /posters/
      # - name: Registration
      #   relative_url: /registration/
      # - name: Attending
      #   relative_url: /location/
      # - name: Important Dates
      #   relative_url: /important_dates/
      # - name: Program
      #   relative_url: /program/
      #   disabled: true
      # - name: Registration
      #   disabled: true
      #   absolute_url: ''

  # Information boxes
  # info_bars:
  #   - title: Mail issues at VUB! 
  #     color: warning
  #     main_only: true
  #     text: Please mail directly to egonzale at vub.be or the PC chair if you are having problems to communicate with us through mplr2022@soft.vub.ac.be.

  #       ---

  #       See the [README](github.com/DigitaleGesellschaft/jekyll-theme-conference/) on the project's GitHub repository for further information on how to configure and adapt it to your needs.
  #   - text: This is just some random content for demonstration purposes.
      # color: warning
  #     pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    time_stop: 240      # in minutes
    streaming:
      time_pause:   60  # in minutes
      time_prepend:  5  # in minutes
      time_extend:   5  # in minutes
    demo: false

  map:
    # Initial map center point
    home_coord: 50.82242, 4.39573
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 15

  talks:
    # Talk categories
    main_categories:
      - name: Paper
        color: success
      # - name: Poster and Demos
      #   color: info

    # Hide icons on talk overview page
    hide_icons: true

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: true

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: false
